# Generated by Django 4.2.30 on 2026-07-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_engine_fields'),
        ('api', '0004_systemalert_alter_databaseserver_environment_type'),
    ]

    operations = [
    ]
